version: '3'
services:
  api:
    image: nerdearla-api
    container_name: api2
    ports:
      - 8600:8600
    command: uvicorn app:app --host 0.0.0.0 --port 8600
    
  app:
    image: nerdearla-api
    container_name: app
    ports:
      - 8601:8501
    command: streamlit run streamlit_app.py
